spring.application.name=api-gateway
server.port=9090

spring.cloud.gateway.mvc.routes[0].id=employee-management-api-route
spring.cloud.gateway.mvc.routes[0].uri=lb://employee-management
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/employees/**


