server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db?createDatabaseIfNotExist=true

spring.cloud.gateway.mvc.routes[0].id=employee-management-employee-route
spring.cloud.gateway.mvc.routes[0].uri=lb://employee-management
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/employees/**

spring.cloud.gateway.mvc.routes[1].id=employee-management-shift-route
spring.cloud.gateway.mvc.routes[1].uri=lb://employee-management
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/shifts/**

spring.cloud.gateway.mvc.routes[2].id=leave-management-balance-route
spring.cloud.gateway.mvc.routes[2].uri=lb://leave-management
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/leave-balances/**

spring.cloud.gateway.mvc.routes[3].id=leave-management-request-route
spring.cloud.gateway.mvc.routes[3].uri=lb://leave-management
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/leave-requests/**

spring.cloud.gateway.mvc.routes[4].id=attendance-management-attendance-route
spring.cloud.gateway.mvc.routes[4].uri=lb://attendance-management
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/attendances/**

spring.cloud.gateway.mvc.routes[5].id=attendance-management-report-route
spring.cloud.gateway.mvc.routes[5].uri=lb://attendance-management
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/attendance-reports/**